apiVersion: v1
kind: ConfigMap
metadata:
  name: rag-config
  namespace: rag-dev
data:
  # Ollama Configuration
  #OLLAMA_BASE_URL: "http://ollama-service:11434"
  #OLLAMA_MODEL: "llama3.2"
  #USE_OLLAMA: "true"
  
  # ChromaDB Configuration
  CHROMA_HOST: "chromadb-service"
  CHROMA_PORT: "8000"
  
  # Redis Configuration
  #REDIS_HOST: "redis-service"
  #REDIS_PORT: "6379"
  
  # Application Configuration
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  #PRIMARY_LLM: "huggingface"
  