# Prometheus Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: rag-dev
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'rag-app'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['backend-svc:8000']           


#Backend service name
