apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-chatbot
type: Opaque
stringData:
  # HuggingFace API Key
  Featherless_ai_key_new: "Featherless_ai_key_new"
  
  # Redis Password (optional)
  REDIS_PASSWORD: ""
