apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-dev
type: Opaque
stringData:
  # HuggingFace API Key
  Featherless_ai_key_new: cmNfMTUwZGZlMDYzNWQ0MzVjMmE2YzI1OTY2MDZmMGViMjc2Zjc4OTJkNDA0NDZmODBjYWQxNzYw
ZmJmMGM0OGYwZg==  #encrypted
  
  #Azure blob storage for chroma db

  CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXJhZ2Jhc2VkZG9jdW1l
bnRzO0FjY291bnRLZXk9OFVZT25XVDBZUElkTDBmWTkyMnByL3A4YlVUOXgzWHFiSmtHb1FxRVNH
bThtdkF0K21zcFBaVTZsQmhhYldISkNMdWdscEtNZmluRCtBU3RUM2pSbGc9PTtFbmRwb2ludFN1
ZmZpeD1jb3JlLndpbmRvd3MubmV0
  

  CONTAINER_NAME: ragdocuments
  
  # Redis Password (optional)
  #REDIS_PASSWORD: ""
