apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-dev
type: Opaque
stringData:
  # HuggingFace API Key
  Featherless_ai_key_new: cmNfMTUwZGZlMDYzNWQ0MzVjMmE2YzI1OTY2MDZmMGViMjc2Zjc4OTJkNDA0NDZmODBjYWQxNzYw
ZmJmMGM0OGYwZg==  #encrypted
  
  # Redis Password (optional)
  #REDIS_PASSWORD: ""
